import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { locales } from "@/config.js";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng}>
      <body>
        <div className="container">
          <Header />
          <div className="main">
            <Sidebar lng={lng} />
            <section className="col note-viewer">{children}</section>
          </div>
        </div>
      </body>
    </html>
  );
}
